name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main   # when you push code to main branch
permissions:
  contents: write # ✅ This allows the action to push to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: true   # ✅ pulls your theme too
            fetch-depth: 0


      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
